baseURL = "https://heewonchung.github.io/"
languageCode = "en-us"
title = "Heewon Chung"
theme = "gokarna"

[params]
  author = "Heewon Chung"
  description = "Professor of Software Engineering at Jeonbuk National University"
  keywords = ["정희원", "암호", "블록체인"]
  #avatarURL = "/images/profile.jpg"  # 프로필 사진
  enableBlogPost = true  # 블로그 기능 활성화

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Research"
    url = "/research/"    
    weight = 3

  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 4

  [[menu.main]]
    name = "Teaching"
    url = "/teaching/"
    weight = 5

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 6
